/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "GUI.h"
#include "app.h"
//#include "DIALOG.h"
#include <string.h>

static char str[50];

static void _cbPop(WM_MESSAGE * pMsg) {
  GUI_RECT   Rect = {0,0,0,0};
  int     xSize;
  int     ySize;
	//WM_HWIN hWin;
	//hWin = pMsg->hWin;
    switch (pMsg->MsgId)
    {
        case WM_PAINT:
            GUI_EnableAlpha(1);
            //GUI_SetAlpha(0xc0);                 // Set alpha value for drawing operations  根据透明程度设置数值
            //GUI_SetBkColor(GUI_BLUE); // Draw gray background... 
            //GUI_Clear();                                // ...with alpha blending 
            xSize = 200;
            ySize = 90;
            //GUI_SetColor(GUI_MAKE_ALPHA(0xA0, GUI_BLACK));
            //GUI_FillRect(0,0,240,320);

            GUI_SetColor(((uint32_t)0x40)<<24|GUI_GREEN);
            GUI_FillRoundedRect(0, 0, xSize -1 , ySize - 1, 10);
            Rect.x1 = xSize - 1;
            Rect.y1 = ySize - 1;
            GUI_SetColor(((uint32_t)0x10)<<24|GUI_RED);
            GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 10);
            //GUI_SetAlpha(0);
            //GUI_EnableAlpha(0);
            GUI_SetFont(&GUI_Font_song16); 
            GUI_SetTextMode(GUI_TM_TRANS);
            GUI_SetColor(GUI_BLACK);
            GUI_DispStringInRectWrap(str, &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER, GUI_WRAPMODE_NONE);
            GUI_EnableAlpha(0);
        //WM_CreateTimer(hWin, 0, 30, 0);	
        break;

         case WM_TIMER:
            GUI_EndDialog(pMsg->hWin, 0);
         //GUI_Delay(10);
         //   GUI_EnableAlpha(0);	
        //WM_RestartTimer(pMsg->Data.v, 1000);
            break;  
    }
}


WM_HWIN  gui_msgbox(const char *s,WM_HWIN hWin)
{
    WM_HWIN  hmsg_box;  
    strcpy(str, s);
    GUI_SetFont(&GUI_Font_song16);
    hmsg_box = WM_CreateWindowAsChild(20, 90, 200, 100, hWin, WM_CF_SHOW|WM_CF_HASTRANS|WM_CF_STAYONTOP, _cbPop,0);
    //WM_CreateTimer(hmsg_box, 0, 1000, 0);
     //WM_EnableMemdev(hmsg_box);
    WM_DisableMemdev(hmsg_box);
    return hmsg_box;
   //WM_SetUserData(hPop, &pText, NumExtraBytes);
}

/*************************** End of file ****************************/
