/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "app.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_MAIN          (GUI_ID_USER + 0x01)
#define ID_ICON_MAIN            (GUI_ID_USER + 0x02)
//#define ID_TEXT_DATE            (GUI_ID_USER + 0x03)
//#define ID_TEXT_TIME            (GUI_ID_USER + 0x04)
#define ID_IMAG_LOGO            (GUI_ID_USER + 0x05)
#define ID_BUTTON_WIFI     	    (GUI_ID_USER + 0x11)
#define ID_PROGBAR_BAT     	    (GUI_ID_USER + 0x12)
#define ID_TEXT_ID_ADDR         (GUI_ID_USER + 0x13)
#define ID_ICON_SERVER          (GUI_ID_USER + 0x14)
// USER START (Optionally insert additional defines)
// USER END
const GUI_BITMAP* WIFI[5] = {&bmnowifi,&bmwifi1,&bmwifi2,&bmwifi3,&bmwifi4};
rt_size_t battery_capity_bar;
extern void run_to_win(rt_uint8_t  WIN_ID);
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "main", ID_WINDOW_MAIN, 0, 0, 240, 320, 0, 0x0, 0 }, 
    //{ BUTTON_CreateIndirect, NULL, ID_BUTTON_WIFI, 0, 0, 34, 30, WM_CF_HASTRANS, 0, 0 },
    { TEXT_CreateIndirect, "date",     ID_TEXT_DATE, 72, 110, 149, 30, 0, 0, 0},
    { TEXT_CreateIndirect, "time",     ID_TEXT_TIME, 88, 140, 149, 30, 0, 0, 0},
    { TEXT_CreateIndirect, "id",       ID_TEXT_ID_ADDR, 90, 280, 149, 30, 0, 0, 0},
    { ICONVIEW_CreateIndirect, "wifi", ID_BUTTON_WIFI, 0,  0, 34,30, WM_CF_HASTRANS, 0x004A0040, 0 },
    //{ ICONVIEW_CreateIndirect, "server", ID_ICON_SERVER, 0,  0, 34,30, WM_CF_HASTRANS, 0x004A0040, 0 },
    { ICONVIEW_CreateIndirect, "icon", ID_ICON_MAIN, 0, 180, 240, 84, WM_CF_HASTRANS, 0x004A0040, 0 },
    { PROGBAR_CreateIndirect, "power", ID_PROGBAR_BAT, 185, 5, 50, 18, 0, 0x0, 0 },
 // { IMAGE_CreateIndirect, "Image", ID_IMAG_LOGO, 81, 27, 60, 65, 0, 0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/


/**/

uint8_t windows_id = 0;
#if 1
void button_set_BKCOLOR(I16 statue,I32 color)
{
	//WM_HWIN button_Win = WM_GetDialogItem(hWin,id);
	BUTTON_SKINFLEX_PROPS Props;
    ///BUTTON_SetSkin()
	//BUTTON_GetSkinFlexProps(&Props, statue);
	Props.aColorFrame[0] = color;
	Props.aColorFrame[1] = color;
	Props.aColorFrame[2] = color;
	Props.aColorLower[0] = color&0xfffff0;
	Props.aColorLower[1] = color&0xfffff0;
	Props.aColorUpper[0] = color;
	Props.aColorUpper[1] = color;
	Props.Radius =2;
	BUTTON_SetSkinFlexProps(&Props, statue);
	//WM_InvalidateWindow(button_Win);
}
#endif


void updata_display(WM_MESSAGE * pMsg)
{
    
    WM_HWIN hItem;
    WM_HWIN hWin = pMsg->hWin;

    char date_buf[] = "2000-00-00";
    char time_buf[] = "00:00:00";
    sprintf(date_buf+2,"%02d-%02d-%02d",runing_time.year,runing_time.month,runing_time.day);
    sprintf(time_buf,"%02d:%02d",runing_time.hour,runing_time.minute);

    TEXT_SetText(WM_GetDialogItem(hWin,ID_TEXT_DATE),date_buf);
    TEXT_SetText(WM_GetDialogItem(hWin,ID_TEXT_TIME),time_buf);   
    hItem = WM_GetDialogItem(hWin, ID_BUTTON_WIFI);
    ICONVIEW_SetBitmapItem(hItem, 0,WIFI[connected_ap.rssi]);
    if(battery_capity_bar > 20)
        PROGBAR_SetBarColor(WM_GetDialogItem(hWin,ID_PROGBAR_BAT),0,0x2fffad);
    else
        PROGBAR_SetBarColor(WM_GetDialogItem(hWin,ID_PROGBAR_BAT),0,GUI_RED);
    PROGBAR_SetValue(WM_GetDialogItem(hWin,ID_PROGBAR_BAT),battery_capity_bar);
    {
        char temp_buf[3] = {0};
        sprintf(temp_buf,"%02d",(int)battery_capity_bar);
        if(100 <= battery_capity_bar)
        {
            battery_capity_bar = 100;
            strncpy(temp_buf,"100",3);
        }
        PROGBAR_SetText(WM_GetDialogItem(hWin,ID_PROGBAR_BAT),temp_buf);
    } 
}

void InitDialog_desktop(WM_MESSAGE * pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin = pMsg->hWin;
	WINDOW_SetBkColor(hWin,0xFF9E3E); /*0xFF9E3E*/
  //GUI_SetFont(&GUI_Font_song16);
	//GUI_DispStringAt("请输入连接密�,40,20);
	ICONVIEW_EnableStreamAuto();
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_WIFI);
	ICONVIEW_SetBkColor(hItem,ICONVIEW_CI_SEL,0xFF9E30);
	ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_LEFT|ICONVIEW_IA_TOP);
	ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_UNSEL, GUI_BLACK);
	ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_SEL, GUI_BLACK);
	ICONVIEW_SetFrame(hItem, GUI_COORD_X, 0);//设置图标到IconView边框的间跍
	ICONVIEW_SetFrame(hItem, GUI_COORD_Y, 0);
	ICONVIEW_SetSpace(hItem, GUI_COORD_X, 0);//设置图标和图标之间的间距
	ICONVIEW_SetSpace(hItem, GUI_COORD_Y, 0);
	ICONVIEW_SetFont(hItem, &GUI_Font16_ASCII);
	ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_UNSEL, 0xFF9E3E);
	ICONVIEW_AddBitmapItem(hItem, WIFI[connected_ap.rssi], "");
	//ICONVIEW_AddBitmapItem(hWin, &button_zw_pay,"指纹付款");//添加图标项ICONVIEW_AddBitmapItem
	//ICONVIEW_AddBitmapItem(hWin, &bmlogo, "商户绑定");
	hItem = WM_GetDialogItem(pMsg->hWin, ID_ICON_MAIN);
	ICONVIEW_SetBkColor(hItem,ICONVIEW_CI_SEL,0xFF9E30);
	ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_TOP);
	ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_UNSEL, GUI_BLACK);
	ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_SEL, GUI_GREEN);
	ICONVIEW_SetFrame(hItem, GUI_COORD_X, 10);//设置图标到IconView边框的间�
	ICONVIEW_SetFrame(hItem, GUI_COORD_Y, 1);
	ICONVIEW_SetSpace(hItem, GUI_COORD_X, 10);//设置图标和图标之间的间距
	ICONVIEW_SetSpace(hItem, GUI_COORD_Y, 10);
	ICONVIEW_SetFont(hItem, &GUI_Font_song16);
	ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_UNSEL, 0xFF9E3E);
	ICONVIEW_AddBitmapItem(hItem, &bmzwzc, "会员注册");
	ICONVIEW_AddBitmapItem(hItem, &button_zw_pay,"指纹收款");//添加图标项ICONVIEW_AddBitmapItem
	ICONVIEW_AddBitmapItem(hItem, &bmid, "商户绑定");
	//WM_SetFocus(hItem);
    ICONVIEW_SetSel(hItem,1);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_DATE);
    TEXT_SetFont(hItem,GUI_FONT_20_ASCII);
    TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetText(hItem,"2017-09-01");
   
    //TEXT_SetTextBkColor(hItem,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TIME);
    TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,GUI_FONT_24_ASCII);
    TEXT_SetText(hItem,"00:00:00");
    
      
    {
        char temp_id_buf[6];
        sprintf(temp_id_buf,"%06x",lzt_dev_id);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ID_ADDR);
        TEXT_SetFont(hItem,GUI_FONT_20_ASCII);
        TEXT_SetTextColor(hItem,GUI_RED);
        TEXT_SetText(hItem,temp_id_buf);
       
    }
    PROGBAR_SetBarColor(WM_GetDialogItem(pMsg->hWin,ID_PROGBAR_BAT),0,0x2fffad);
    PROGBAR_SetMinMax(WM_GetDialogItem(pMsg->hWin,ID_PROGBAR_BAT), 0, 100);
    PROGBAR_SetValue(WM_GetDialogItem(pMsg->hWin,ID_PROGBAR_BAT),battery_capity_bar);
    {
        char temp_buf[3] = {0};
        sprintf(temp_buf,"%02d",(int)battery_capity_bar);
        if(100 >= battery_capity_bar)
        {
            battery_capity_bar = 100;
            strncpy(temp_buf,"100",3);
        }
        PROGBAR_SetText(WM_GetDialogItem(pMsg->hWin,ID_PROGBAR_BAT),temp_buf);
    }        
    //Value = PROGBAR_GetValue(WM_GetDialogItem(hItem,ID_PROGBAR_BAT)); 
    ///PROGBAR_SetValue(WM_GetDialogItem(pMsg->hWin,ID_PROGBAR_BAT), battery_capity_bar);
    /*BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_WIFI),BUTTON_CI_UNPRESSED,0xFF9E3E);
    BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_WIFI), 0);
    BUTTON_SetBitmapEx(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_WIFI),BUTTON_CI_UNPRESSED,WIFI[connected_ap.rssi],1,0);
    button_set_BKCOLOR(BUTTON_SKINFLEX_PI_ENABLED,0xFF9E3E);*/	
		
	
	
}


static void _cb_main_Dialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    //win_msg_t wmsg;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
        case WM_PAINT:
        {
            GUI_DrawBitmap(&bmlogo,70,30);
            hItem = pMsg->hWin;
            WINDOW_SetBkColor(hItem, 0x00FF9E3E);
            //GUI_SetColor(GUI_BLUE);
            //GUI_DrawHLine(55,20,219);   //间隔�  
        }
        break;
        case WM_INIT_DIALOG:
        {
            //
            // Initialization of 'main'
            //			
            InitDialog_desktop(pMsg);
            updata_display(pMsg);
            // USER START (Optionally insert additional code for further widget initialization)
          
            // USER END
        }
        break;
        //case MSG_SetICONFocus:
            //WM_SetFocus(WM_GetDialogItem(hItem,ID_ICON_MAIN));
        //break;
        case WM_USER:
            updata_display(pMsg);
            break;
        case WM_NOTIFY_PARENT:
        {
            
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            hItem = pMsg->hWin;
            switch(Id)
            {
                case ID_ICON_MAIN: // Notifications sent by 'finger_pay'
                {
                    switch(NCode)
                    {
                        case WM_NOTIFICATION_RELEASED:
                        {
                            rt_uint8_t msg[4]={0};
                            rt_uint8_t iconview_idx = ICONVIEW_GetSel(WM_GetDialogItem(hItem,ID_ICON_MAIN));
                            #if 0
                            switch(ICONVIEW_GetSel(WM_GetDialogItem(hItem,ID_ICON_MAIN)))
                            {
                                /* 会员注册 */
                                case 0:
                                    //Creat_user_phone_input();
                                    run_to_win(ID_TASK_USER_REGISTER_PHONE);
                                    //PROCESS_STATUS = TASK_USER_REGIST;
                                    break;
                                /*指纹付款*/
                                case 1:
                                    run_to_win(ID_TASK_PAY_NUM);
                                    //PROCESS_STATUS = TASK_PAY;
                                    break;
                                /*商户绑定*/
                                case 2:
                                    run_to_win(ID_TASK_OWNER_REGISTER_PHONE);
                                    //PROCESS_STATUS = TASK_OWNER_REGIST;
                                    break;
                                default:
                                    break;									
                            }
                            #endif                           
                            msg[1] = RETURN_FROM_WIN;
                            msg[0] = ID_TASK_MAIN;
                            msg[2] = iconview_idx;
                            rt_mq_send(&wmq,msg,4);
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                        }
                        break;
                        case WM_NOTIFICATION_CLICKED:
                        {   
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        }
                    }
                    break;
                    default:
                    break;
                }
              case ID_BUTTON_WIFI: // Notifications sent by 'password'
                switch(NCode) 
                {
            
                    case WM_NOTIFICATION_RELEASED:
                    {
                        rt_uint8_t msg[4]={0};
                        rt_uint8_t wifi_image_id = 55;                          
                        msg[1] = RETURN_FROM_WIN;
                        msg[0] = ID_TASK_MAIN;
                        msg[2] = wifi_image_id;
                        rt_mq_send(&wmq,msg,4);
                    }
                        //Createwifi_list();
                        //PROCESS_STATUS = TASK_MAIN;
                    break;
                }
                break;	
            }
              
            
        }
        break;
        default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createmain
*/
WM_HWIN Createmain(void);
WM_HWIN Createmain(void) 
{
  WM_HWIN hWin;
  GUI_UC_SetEncodeUTF8();
  GUI_SetFont(&GUI_Font_song16);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cb_main_Dialog,WM_HBKWIN, 0, 0);
    //hWin =WM_CreateWindow();
  //WM_EnableMemdev(hWin);
  return hWin;
}
void MainTask(void)
{
	//WM_SetCreateFlags(WM_CF_MEMDEV);
	//if(windows_id == 0)
		//Createmain();
	//else if(1 == windows_id)
		//CreateFp_regedit();
	//else if(2 == windows_id)
	//Creat_Pay_input();
	//Createtest();
	 //Createwifi_jap();
	//CreatenotificationBar();
	///Createdenglu();
	//if(0!= wifi_list_AP[0].ssid[0])
	 Createwifi_list();
	 //CreateFp_regedit();
	 //WM_EnableMemdev(WM_HBKWIN);
	 //IMAGE_SetJPEG(WM_HBKWIN,&bmwifi4,12500);
	//Creat_phonenum_input();
	/*while(1)
	{
		GUI_Delay(100);
	}*/
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
