/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "app.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_PAY              	(GUI_ID_USER + 0x24)
#define ID_EDIT_PAY_NUMBER     		(GUI_ID_USER + 0x25)
#define ID_BUTTON_PAY_EXIT         	(GUI_ID_USER + 0x26)
//#define ID_BUTTON_PAY_ENT          	(GUI_ID_USER + 0x27)
#define ID_TEXT_PAY_PROMPT          (GUI_ID_USER + 0x28)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "pay", ID_WINDOW_PAY, 0, 0, 240, 320, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "num", ID_EDIT_PAY_NUMBER, 20, 70, 200, 30, 0, 0x07, 0 },
  { BUTTON_CreateIndirect, "EXTI",   ID_BUTTON_PAY_EXIT, 170, 22, 60, 40, 0, 0, 0 },
  //{ BUTTON_CreateIndirect, "enter",   ID_BUTTON_PAY_ENT, 160, 70, 60, 30, 0, 0, 0 },
  { TEXT_CreateIndirect, "txt1",     ID_TEXT_PAY_PROMPT, 20, 35, 200, 30, 0, 0, 0},
  // USER START (Optionally insert additional widgets)
  // USER END
};
//extern WM_HWIN hMulti;
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  //WM_HWIN hWin;  
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END
  //char buf[12];
  //hWin = pMsg->hWin;
  switch (pMsg->MsgId)
	{
		case WM_INIT_DIALOG:
			hItem = pMsg->hWin;
			WINDOW_SetBkColor(hItem, 0x00FF9E3E);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PAY_PROMPT);
			TEXT_SetFont(hItem,&GUI_Font_song16);
			TEXT_SetText(hItem,"请您输入身份识别码");
			TEXT_SetTextColor(hItem,GUI_BLACK);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PAY_EXIT);
			BUTTON_SetFont(hItem,&GUI_Font_song16);
			BUTTON_SetText(hItem,"取消");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);					
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_PAY_NUMBER);
			EDIT_SetText(hItem, "");
			EDIT_SetTextAlign(hItem,  GUI_TA_CENTER|GUI_TA_VCENTER);
			EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00000000);
			EDIT_SetFont(hItem, GUI_FONT_20_1);
			WM_SetFocus(hItem);
			// USER START (Optionally insert additional code for further widget initialization)
			// USER END
			break;
		case WM_PAINT:
			break;
        case WM_KEY:
            switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key)
            {  //char read_buf[22];
                
                case GUI_KEY_ENTER:
                    {
                        //win_msg_union_t msg;
                        char buf[10];
                        EDIT_GetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_PAY_NUMBER),buf,8);
                        EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_PAY_NUMBER), "");
                        send_frame_package(CMD_SEND_UDID,0,buf,RT_NULL);
                        /*msg.msg.id_operate = SEND_TO_SERVE;
                        msg.msg.id_win = ID_TASK_PAY_UDID;
                        rt_mq_send(&wmq,msg.buf,rt_strlen(msg.buf));*/
                       // WM_DeleteWindow(hWin);
                    }
                    //GUI_EndDialog(hDlg, 0);
                    break;
                default:
                    break;
            }
            break;
		case WM_NOTIFY_PARENT:
            hItem = pMsg->hWin;
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch(Id) 
			{
					case ID_EDIT_PAY_NUMBER: // Notifications sent by 'password'
						switch(NCode) 
						{
							case WM_NOTIFICATION_CLICKED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
								break;
							case WM_NOTIFICATION_RELEASED:
                                
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
								break;
							case WM_NOTIFICATION_VALUE_CHANGED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
								break;
							// USER START (Optionally insert additional code for further notification handling)
							// USER END
							default:
								break;
						}
						break;
				case ID_BUTTON_PAY_EXIT: // Notifications sent by 'Button'
					switch(NCode) 
					{
						case WM_NOTIFICATION_CLICKED:
							// USER START (Optionally insert code for reacting on notification message)
							// USER END
							break;
						case WM_NOTIFICATION_RELEASED:
                        {
                            run_to_win(ID_TASK_PAY_NUM);
                        }
                        break;
						// USER START (Optionally insert additional code for further notification handling)
						// USER END
						default:
								break;
						}
					break;	
				default:
					break;
			}
			break;
		// USER START (Optionally insert additional message handling)
		// USER END
		default:
			WM_DefaultProc(pMsg);
			break;
		}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createwifi_jap
*/
WM_HWIN Creat_Pay_UDID(void);
WM_HWIN Creat_Pay_UDID(void)
{
    WM_HWIN hWin;
    GUI_UC_SetEncodeUTF8();
    GUI_SetFont(&GUI_Font_song16);
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog,WM_HBKWIN, 0, 0);
    //WM_EnableMemdev(hWin);
    //HwinCurr_Keyboard = keyboard_num(hWin);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
