Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'lzt')

if GetDepend('RT_USING_LZT_APP'):
    src = Split("""
	app.c
	app_msgbox.c
	Fp_regist1.c
	Fp_regist2.c
	Fp_regist3.c
	keyboard.c
	payDLG.c
	payUDID.c
	user_phone_input.c
	owner_phone_input.c
	user_validation_input.c
	owner_validation_input.c
	mainDLG.c
	wifi_japDLG.c
	wifi_list.c
	""")
if GetDepend('RT_USING_CAN'):
    src += ['canapp.c']

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('lzt', src, depend = ['RT_USING_LZT_APP'], CPPPATH = CPPPATH)

Return('group')
