/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "app.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_JAP              		(GUI_ID_USER + 0x30)
//#define ID_TEXT_JAP_SSID     			(GUI_ID_USER + 0x31)
#define ID_EDIT_JAP_SSID     			(GUI_ID_USER + 0x32)
#define ID_EDIT_JAP_PASSWORD     		(GUI_ID_USER + 0x33)
#define ID_BUTTON_JAP_CANCEL         	(GUI_ID_USER + 0x34)
#define ID_BUTTON_JAP_CONNECT       	(GUI_ID_USER + 0x35)
#define ID_TEXT_SSID_TIP            	(GUI_ID_USER + 0x36)
#define ID_TEXT_PASSWORD_TIP            (GUI_ID_USER + 0x37)
// USER START (Optionally insert additional defines)
// USER END
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_song16, GUI_Font_kai20S, GUI_Font_kai24;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "wifi_jap", 	ID_WINDOW_JAP, 			0, 		0, 		240, 	320, 	0, 	0, 		0 },
  { TEXT_CreateIndirect, "SSID",   		ID_TEXT_SSID_TIP, 		2, 		8, 		34, 	30, 	0, 	0, 	0 },
  { EDIT_CreateIndirect, "ssid", 		ID_EDIT_JAP_SSID, 		36, 	2, 		200, 	30, 	0, 	22, 	0 },
  { TEXT_CreateIndirect, "password",   	ID_TEXT_PASSWORD_TIP, 	2, 		36, 	34, 	30, 	0, 	0, 		0 },
  { EDIT_CreateIndirect, "password", 	ID_EDIT_JAP_PASSWORD, 	36, 	32, 	200, 	30, 	0, 	22, 	0 },
  { BUTTON_CreateIndirect, "CANCEL",   	ID_BUTTON_JAP_CANCEL, 	20, 	80, 	60, 	40, 	0, 	0, 		0 },
  { BUTTON_CreateIndirect, "CONNECT",   ID_BUTTON_JAP_CONNECT, 	160, 	80, 	60, 	40, 	0, 	0, 		0 },
 
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
//WM_HWIN hkbd;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	// USER START (Optionally insert additional variables)
//	WM_HWIN hWinCurrent;
	// USER END
	//hWinCurrent = pMsg->hWin; 
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
            {
                //
                // Initialization of 'wifi_jap'
                //
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, 0x00FF9E3E);	
                BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
                 //GUI_UC_SetEncodeUTF8();
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SSID_TIP);
                TEXT_SetFont(hItem,&GUI_Font16_ASCII);			
                TEXT_SetText(hItem,"SSID");
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PASSWORD_TIP);
                TEXT_SetFont(hItem,&GUI_Font_song16);
                TEXT_SetText(hItem,"密码");
                TEXT_SetTextColor(hItem,GUI_BLACK);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_JAP_PASSWORD);
                EDIT_SetFont(hItem, GUI_FONT_20_1);
                EDIT_SetText(hItem, "");
                EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
                EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x00000000);			
                WM_SetFocus(hItem);			
                
                // USER START (Optionally insert additional code for further widget initialization)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_JAP_CANCEL);
                BUTTON_SetFont(hItem,&GUI_Font_song16);
                BUTTON_SetText(hItem,"取消");
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_JAP_CONNECT);
                BUTTON_SetFont(hItem,&GUI_Font_song16);
                BUTTON_SetText(hItem,"连接");
                // USER END
            }
            break;
        case WM_KEY:
            switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key)
            {    
                 
                case GUI_KEY_ENTER:
                {   
                    char ssid_buf[22] = {0};
                    char password_buf[23] = {0};
                    char buf[50] = {0};
                    //union win_msg_union xmsg;
                    //hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_JAP_SSID);
                    EDIT_GetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_JAP_SSID),ssid_buf,22);
                   // hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_JAP_PASSWORD);
                    EDIT_GetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_JAP_PASSWORD),password_buf+1,22);
                    password_buf[0] = ',';
                    strcpy(buf+2,ssid_buf);
                    strcat(buf+2,password_buf);
                    buf[1] = SEND_TO_SERVE;
                    buf[0] = ID_TASK_JOAP_WIFI;
                    rt_mq_send(&wmq,buf,rt_strlen(buf));
                    hItem = pMsg->hWin;
                    WM_DeleteWindow(hItem);
                }
                    break;
                default:
                    break;
            }
            break;
		case WM_NOTIFY_PARENT:
		{
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch(Id) 
			{
				case ID_EDIT_JAP_PASSWORD: // Notifications sent by 'password'
				{
					switch(NCode) 
					{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
					case WM_NOTIFICATION_RELEASED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
					case WM_NOTIFICATION_VALUE_CHANGED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
					// USER START (Optionally insert additional code for further notification handling)
					// USER END
					}
				}
				break;
				case ID_BUTTON_JAP_CANCEL: // Notifications sent by 'Button'
				{
					switch(NCode) 
					{
						case WM_NOTIFICATION_CLICKED:
						
						break;
						case WM_NOTIFICATION_RELEASED:
                        {
                            win_msg_union_t msg;
                            msg.msg.id_operate = RETURN_FROM_WIN;
                            msg.msg.id_win = ID_TASK_JOAP_WIFI;
                            ////WM_DeleteWindow(HwinCurr_Keyboard);
                            rt_mq_send(&wmq,msg.buf,rt_strlen(msg.buf));
                        }
                        break;
                    }
				}
				break;	
				case ID_BUTTON_JAP_CONNECT: // Notifications sent by 'Button'
				{
					switch(NCode) 
					{
						case WM_NOTIFICATION_CLICKED:
						{
							// USER START (Optionally insert code for reacting on notification message)
							
							// USER END
						}
						break;
						case WM_NOTIFICATION_RELEASED:
                          {   
                                char ssid_buf[22] = {0};
                                char password_buf[23] = {0};
                                char buf[50] = {0};
                                //union win_msg_union xmsg;
                                //hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_JAP_SSID);
                                EDIT_GetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_JAP_SSID),ssid_buf,22);
                               // hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_JAP_PASSWORD);
                                EDIT_GetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_JAP_PASSWORD),password_buf+1,22);
                                password_buf[0] = ',';
                                strcpy(buf+2,ssid_buf);
                                strcat(buf+2,password_buf);
                                buf[1] = SEND_TO_SERVE;
                                buf[0] = ID_TASK_JOAP_WIFI;
                                ////WM_DeleteWindow(HwinCurr_Keyboard);
                                rt_mq_send(&wmq,buf,rt_strlen(buf));
                                hItem = pMsg->hWin;
                                
                                //WM_DeleteWindow(hItem);
                            }
						break;
						// USER START (Optionally insert additional code for further notification handling)
						// USER END
					}
				}
				break;	
				// USER START (Optionally insert additional code for further Ids)
				// USER END
			}
			break;
			// USER START (Optionally insert additional message handling)
			// USER END
		}
		default:
			WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createwifi_jap
*/

WM_HWIN Createwifi_jap(char *buffer);
WM_HWIN Createwifi_jap(char *buffer) 
{
	WM_HWIN hWin,hItem;
	//GUI_UC_SetEncodeUTF8();
	//GUI_SetFont(&GUI_Font_song16);
	char *temp_buff = buffer;
	hWin = GUI_CreateDialogBox(_aDialogCreate,GUI_COUNTOF(_aDialogCreate) , _cbDialog, WM_HBKWIN, 0, 0);
	hItem = WM_GetDialogItem(hWin, ID_EDIT_JAP_SSID);
    EDIT_SetFont(hItem, GUI_FONT_20_1);
    EDIT_SetText(hItem, temp_buff);
    //WM_EnableMemdev(hWin);
	//HwinCurr_Keyboard = keyboard_num(hWin);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
