/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: _kai24.c                                              *
* Font:        ¿¬Ìå                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\desktop\¿¬24.txt                             *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_kai24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font_kai24_4EE3[ 57] = { /* code 4EE3 */
  ________,__XXX_XX,X_______,
  _______X,___XX__X,XX______,
  ______XX,___XX___,_X______,
  ______XX,___XX___,________,
  ______X_,____X___,________,
  _____XX_,____X__X,XX______,
  _____X__,____XXXX,________,
  ____XXX_,____XX__,________,
  ____X_X_,_XXX_X__,________,
  ___X__X_,_____X__,________,
  __X___X_,_____XX_,________,
  _X____X_,______X_,________,
  ______X_,______XX,________,
  ______X_,_______X,X_______,
  ______X_,________,X___X___,
  ______X_,________,XX__X___,
  _____XX_,________,_XXXX___,
  ______X_,________,__XXX___,
  ________,________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Font_kai24_604B[ 60] = { /* code 604B */
  ________,XX______,________,
  ________,_XX_____,________,
  ________,_____XXX,X_______,
  ________,XXXXXXX_,________,
  ___XXXXX,___X____,________,
  _______X,___X____,________,
  _______X,___X____,________,
  ___X___X,___X___X,X_______,
  ___X___X,___X____,XX______,
  __XX___X,___X____,_X______,
  __XX___X,___X____,________,
  _______X,___X____,________,
  ________,________,________,
  __X_____,_XX____X,XX______,
  __X_____,__X_____,XXX_____,
  _XX__X__,________,_XXX____,
  _XX__X__,______X_,________,
  _X____X_,______X_,________,
  _______X,XXXXXXXX,X_______,
  ________,_XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_kai24_6307[ 60] = { /* code 6307 */
  ______XX,________,________,
  _______X,___XX___,_X______,
  _______X,___XX___,XX______,
  _______X,___XX_XX,________,
  _______X,___XXX__,________,
  _______X,XX_X____,___X____,
  _____XXX,X___X___,__XXX___,
  __XXXX_X,____XXXX,XXXX____,
  _______X,_X______,________,
  _______X,X_______,________,
  ______XX,___XXXXX,XXXX____,
  ____XX_X,___XX___,__XX____,
  ___XX__X,____X___,__X_____,
  _XXX___X,____XXXX,X_X_____,
  __X____X,____X___,__X_____,
  _______X,____X___,__X_____,
  _____XXX,___XX_XX,X_X_____,
  ______XX,___XXX__,_XX_____,
  ______X_,________,__X_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_kai24_65F6[ 66] = { /* code 65F6 */
  ________,_____X__,________,
  ________,_____XX_,________,
  ________,______X_,________,
  _____X__,______X_,________,
  _XXXXXX_,______X_,________,
  _X___XX_,______X_,________,
  _X___XX_,______X_,__X_____,
  _X___XX_,__XXXXXX,XXXX____,
  _X___XXX,XXX___X_,________,
  _X_XXXX_,______X_,________,
  _XX__XX_,______X_,________,
  _X___XX_,_XX___X_,________,
  _X___XX_,__XX__X_,________,
  _X___XX_,______X_,________,
  _X___XX_,______X_,________,
  _XXXXXX_,______X_,________,
  _X___X__,______X_,________,
  ________,___X__X_,________,
  ________,____XXX_,________,
  ________,_____XX_,________,
  ________,_____X__,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Font_kai24_CharInfo[4] = {
   {  22,  19,   1,   3,  24, acGUI_Font_kai24_4EE3 } /* code 4EE3 */
  ,{  20,  20,   2,   2,  24, acGUI_Font_kai24_604B } /* code 604B */
  ,{  21,  20,   1,   3,  24, acGUI_Font_kai24_6307 } /* code 6307 */
  ,{  21,  22,   2,   2,  24, acGUI_Font_kai24_65F6 } /* code 65F6 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font_kai24_Prop4 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Font_kai24_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font_kai24_Prop3 = {
   0x6307 /* first character */
  ,0x6307 /* last character  */
  ,&GUI_Font_kai24_CharInfo[  2] /* address of first character */
  ,&GUI_Font_kai24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font_kai24_Prop2 = {
   0x604B /* first character */
  ,0x604B /* last character  */
  ,&GUI_Font_kai24_CharInfo[  1] /* address of first character */
  ,&GUI_Font_kai24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font_kai24_Prop1 = {
   0x4EE3 /* first character */
  ,0x4EE3 /* last character  */
  ,&GUI_Font_kai24_CharInfo[  0] /* address of first character */
  ,&GUI_Font_kai24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font_kai24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font_kai24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

