/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: _Font_kai20S.c                                        *
* Font:        楷体                                                  *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_Font_kai20S;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font_Font_kai20S_4ED8[ 60] = { /* code 4ED8 */
  ________,________,________,
  ________,________,________,
  ________,___X____,__XX____,
  ________,___XX___,__X_____,
  ________,__XX____,__X_____,
  ________,_XX_____,_X______,
  ________,_X______,_X______,
  ________,X_______,_XXX____,
  _______X,X_XXXXXX,X_______,
  ______X_,X_______,X_______,
  _____X__,X__X____,X_______,
  ___XX__X,___XX__X,________,
  __X____X,___X___X,________,
  _______X,_______X,________,
  ______X_,______X_,________,
  ______X_,______X_,________,
  _____X__,____XXX_,________,
  ________,_____X__,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_Font_kai20S_56E2[ 60] = { /* code 56E2 */
  ________,________,________,
  ________,________,________,
  ________,________,__XX____,
  ________,_XXXXXXX,XX_X____,
  ________,XX____XX,___X____,
  ________,X_____X_,___X____,
  ________,X_____X_,___X____,
  _______X,____XXXX,X_XX____,
  _______X,___X_X__,__X_____,
  _______X,____XX__,__X_____,
  ______X_,___X_X__,__X_____,
  ______X_,_XX_X___,_X______,
  ______XX,X___X___,_X______,
  _____X__,___XX___,XX______,
  _____X__,___X____,X_______,
  ____X___,_XXXXXXX,X_______,
  ____XXXX,X______X,X_______,
  ________,_______X,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_Font_kai20S_604B[ 60] = { /* code 604B */
  ________,________,________,
  ________,_____XX_,________,
  ________,______XX,________,
  ________,________,XXXX____,
  ________,XXXXXXXX,________,
  ________,____X__X,________,
  ________,___X__X_,________,
  ________,X__X__X_,_XX_____,
  _______X,___X__X_,__XX____,
  ______XX,__X__XX_,________,
  ______X_,__X__X__,________,
  ________,________,________,
  ________,___X____,XX______,
  ____X___,___X____,_XX_____,
  ___XX__X,______X_,__X_____,
  ___X___X,______X_,________,
  _______X,XX___XXX,________,
  ________,_XXXXXX_,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_Font_kai20S_6307[ 60] = { /* code 6307 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,___X___X,___X____,
  ________,___X___X,__XX____,
  ________,__X___X_,XX______,
  ________,__X___XX,________,
  ________,XXXX__X_,___X____,
  ______XX,_X____XX,XXXX____,
  ________,_XX_____,________,
  ________,XX__X__X,XXX_____,
  ______XX,X___XXX_,__X_____,
  ____XX__,X___X___,_X______,
  ___XX___,X___XXX_,_X______,
  _______X,___X____,_X______,
  _______X,___X____,XX______,
  ______X_,__X_XXXX,X_______,
  ______X_,_______X,X_______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_Font_kai20S_652F[ 60] = { /* code 652F */
  ________,________,________,
  ________,_____X__,________,
  ________,_____XX_,________,
  ________,_____XX_,________,
  ________,_____X__,________,
  ________,____XXXX,X_______,
  ________,_XXXX___,________,
  ________,____X___,________,
  ________,___X__X_,________,
  ________,__XXXXXX,________,
  _______X,XX___X__,________,
  _______X,____X___,________,
  ________,X__XX___,________,
  ________,_X_X____,________,
  ________,_XX_____,________,
  ________,X__XX___,________,
  _____XXX,___XXXX_,________,
  __XXX___,____XXXX,XX______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_Font_kai20S_7EB9[ 60] = { /* code 7EB9 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_XX____X,XX______,
  ________,_X______,XX______,
  ________,X_X_____,________,
  _______X,__X_____,________,
  ______X_,_X_____X,XXX_____,
  _____XXX,X__XXXXX,________,
  _______X,_______X,________,
  ______X_,___X__X_,________,
  _____XXX,X___X_X_,________,
  ____X___,____XX__,________,
  _______X,X___XX__,________,
  ____XXX_,__XX_XXX,________,
  ___XX___,XX____XX,XXX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font_Font_kai20S_CharInfo[6] = {
   {  20,  20,  3, acGUI_Font_Font_kai20S_4ED8 } /* code 4ED8 */
  ,{  20,  20,  3, acGUI_Font_Font_kai20S_56E2 } /* code 56E2 */
  ,{  20,  20,  3, acGUI_Font_Font_kai20S_604B } /* code 604B */
  ,{  20,  20,  3, acGUI_Font_Font_kai20S_6307 } /* code 6307 */
  ,{  20,  20,  3, acGUI_Font_Font_kai20S_652F } /* code 652F */
  ,{  20,  20,  3, acGUI_Font_Font_kai20S_7EB9 } /* code 7EB9 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_Font_kai20S_Prop6 = {
   0x7EB9 /* first character */
  ,0x7EB9 /* last character  */
  ,&GUI_Font_Font_kai20S_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_Font_kai20S_Prop5 = {
   0x652F /* first character */
  ,0x652F /* last character  */
  ,&GUI_Font_Font_kai20S_CharInfo[  4] /* address of first character */
  ,&GUI_Font_Font_kai20S_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_Font_kai20S_Prop4 = {
   0x6307 /* first character */
  ,0x6307 /* last character  */
  ,&GUI_Font_Font_kai20S_CharInfo[  3] /* address of first character */
  ,&GUI_Font_Font_kai20S_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_Font_kai20S_Prop3 = {
   0x604B /* first character */
  ,0x604B /* last character  */
  ,&GUI_Font_Font_kai20S_CharInfo[  2] /* address of first character */
  ,&GUI_Font_Font_kai20S_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_Font_kai20S_Prop2 = {
   0x56E2 /* first character */
  ,0x56E2 /* last character  */
  ,&GUI_Font_Font_kai20S_CharInfo[  1] /* address of first character */
  ,&GUI_Font_Font_kai20S_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_Font_kai20S_Prop1 = {
   0x4ED8 /* first character */
  ,0x4ED8 /* last character  */
  ,&GUI_Font_Font_kai20S_CharInfo[  0] /* address of first character */
  ,&GUI_Font_Font_kai20S_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font_kai20S = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font_Font_kai20S_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

